#BUILD stage
FROM maven:3.9.9-eclipse-temurin-17 AS builder


WORKDIR /app


COPY pom.xml .
copy src ./src

RUN mvn clean package -DskipTests


# Runtime Stage

FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

copy --from=builder /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","app.jar"]




